export const JOUR_DEPART_REQUEST = "JOUR_DEPART_REQUEST";
export const JOUR_DEPART_SUCCESS = "JOUR_DEPART_SUCCESS";
export const JOUR_DEPART_FAIL = "JOUR_DEPART_FAIL";
export const JOUR_DEPART_RESET = "JOUR_DEPART_RESET";

export const USER_DEPART_REQUEST = "USER_DEPART_REQUEST";
export const USER_DEPART_SUCCESS = "USER_DEPART_SUCCESS";
export const USER_DEPART_FAIL = "USER_DEPART_FAIL";
export const USER_DEPART_RESET = "USER_DEPART_RESET";

export const HEURE_SINGLE_REQUEST= "HEURE_SINGLE_REQUEST";
export const HEURE_SINGLE_SUCCESS = "HEURE_SINGLE_SUCCESS";
export const HEURE_SINGLE_FAIL = "HEURE_SINGLE_FAIL";
export const HEURE_SINGLE_RESET = "HEURE_SINGLE_RESET";

export const HEURE_DERNIER_REQUEST= "HEURE_DERNIER_REQUEST";
export const HEURE_DERNIER_SUCCESS = "HEURE_DERNIER_SUCCESS";
export const HEURE_DERNIER_FAIL = "HEURE_DERNIER_FAIL";
export const HEURE_DERNIER_RESET = "HEURE_DERNIER_RESET";